include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'example/**'
    - 'packages/**'
    - 'tools/**'
    - 'demo/**'

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
