targets:
  $default:
    builders:
      drift_dev:
        options:
          # Lets use string to store time same between postgres and sqlite
          store_date_time_values_as_text: true
          sql:
            dialects:
              - postgres
              - sqlite
