/// Web-compatible type stubs for native-only tfc_mcp_server implementations.
///
/// These types exist so that conditional imports resolve on web.
/// They should never be instantiated on web — the provider layer returns null.

import 'interfaces/drawing_index.dart';
import 'interfaces/plc_code_index.dart';
import 'interfaces/tech_doc_index.dart';
import 'identity/operator_identity.dart';
import 'services/plc_code_service.dart' show KeyMappingLookup;
import 'tools/tool_toggles.dart';

// ---------------------------------------------------------------------------
// TfcMcpServer — native MCP server, not available on web
// ---------------------------------------------------------------------------
class TfcMcpServer {
  TfcMcpServer({
    dynamic identity,
    dynamic database,
    dynamic stateReader,
    dynamic alarmReader,
    dynamic drawingIndex,
    dynamic plcCodeIndex,
    dynamic techDocIndex,
    dynamic toggles,
    dynamic mcpServer,
    dynamic logger,
    dynamic onProposal,
  });

  dynamic get mcpServer =>
      throw UnsupportedError('TfcMcpServer not available on web');

  Future<void> connect(dynamic transport) async =>
      throw UnsupportedError('TfcMcpServer.connect not available on web');

  Future<void> close({bool closeDatabase = true}) async =>
      throw UnsupportedError('TfcMcpServer.close not available on web');
}

// ---------------------------------------------------------------------------
// Drift-backed index implementations — not available on web
// ---------------------------------------------------------------------------
class DriftDrawingIndex implements DrawingIndex {
  DriftDrawingIndex(dynamic db);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
      throw UnsupportedError('DriftDrawingIndex not available on web');
}

class DriftTechDocIndex implements TechDocIndex {
  DriftTechDocIndex(dynamic db);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
      throw UnsupportedError('DriftTechDocIndex not available on web');
}

class DriftPlcCodeIndex implements PlcCodeIndex {
  DriftPlcCodeIndex(dynamic db);

  Future<List<PlcVarRefTableData>> getVarRefsForBlock(int blockId) async =>
      throw UnsupportedError('DriftPlcCodeIndex not available on web');

  Future<List<PlcFbInstanceTableData>> getFbInstances({
    String? fbTypeName,
    String? instanceName,
  }) async =>
      throw UnsupportedError('DriftPlcCodeIndex not available on web');

  Future<List<PlcBlockCallTableData>> getBlockCalls(int blockId) async =>
      throw UnsupportedError('DriftPlcCodeIndex not available on web');

  Future<List<PlcVarRefTableData>> getVarRefs(String variablePath) async =>
      throw UnsupportedError('DriftPlcCodeIndex not available on web');

  Future<int> reindexAsset(String assetKey) async =>
      throw UnsupportedError('DriftPlcCodeIndex not available on web');

  @override
  dynamic noSuchMethod(Invocation invocation) =>
      throw UnsupportedError('DriftPlcCodeIndex not available on web');
}

// ---------------------------------------------------------------------------
// Drift table data stubs — these are generated by drift in the real code
// ---------------------------------------------------------------------------
class PlcVarRefTableData {
  @override
  dynamic noSuchMethod(Invocation invocation) =>
      throw UnsupportedError('PlcVarRefTableData not available on web');
}

class PlcFbInstanceTableData {
  @override
  dynamic noSuchMethod(Invocation invocation) =>
      throw UnsupportedError('PlcFbInstanceTableData not available on web');
}

class PlcBlockCallTableData {
  @override
  dynamic noSuchMethod(Invocation invocation) =>
      throw UnsupportedError('PlcBlockCallTableData not available on web');
}

// ---------------------------------------------------------------------------
// EnvOperatorIdentity — uses dart:io, not available on web
// ---------------------------------------------------------------------------
class EnvOperatorIdentity implements OperatorIdentity {
  EnvOperatorIdentity({Map<String, String>? env});

  @override
  dynamic noSuchMethod(Invocation invocation) =>
      throw UnsupportedError('EnvOperatorIdentity not available on web');
}

// ---------------------------------------------------------------------------
// ServerDatabase / ServerDatabaseConfig — drift + postgres, not on web
// ---------------------------------------------------------------------------
class ServerDatabase {
  ServerDatabase._();
}

class ServerDatabaseConfig {
  ServerDatabaseConfig._();
}

// ---------------------------------------------------------------------------
// Audit / Safety / Logging — native-only
// ---------------------------------------------------------------------------
class AuditLogService {
  AuditLogService._();
}

class SafetyScanner {
  SafetyScanner._();
}

class StderrLogger {
  StderrLogger._();
}

class ElicitationRiskGate {
  ElicitationRiskGate._();
}

// ---------------------------------------------------------------------------
// Drift-backed services — native-only
// ---------------------------------------------------------------------------
class AlarmService {
  AlarmService._();
}

class ConfigService implements KeyMappingLookup {
  ConfigService(dynamic db);

  @override
  Future<List<Map<String, dynamic>>> listKeyMappings({
    String? filter,
    int limit = 50,
  }) async =>
      throw UnsupportedError('ConfigService not available on web');
}

class TrendService {
  TrendService._();
}

class ProposalService {
  ProposalService._();
}

// ---------------------------------------------------------------------------
// ProposalCallback — typedef from proposal_service.dart
// ---------------------------------------------------------------------------
typedef ProposalCallback = void Function(Map<String, dynamic> wrapped);

// ---------------------------------------------------------------------------
// readMcpConfigFromPreferences — stub for web (original imports preferences.dart)
// ---------------------------------------------------------------------------
Future<McpConfig> readMcpConfigFromPreferences(dynamic prefs) async =>
    const McpConfig();

Future<void> writeMcpConfigToPreferences(
    dynamic prefs, McpConfig config) async {}

Future<McpToolToggles> readTogglesFromPreferences(dynamic prefs) async =>
    McpToolToggles.allEnabled;
