# install-cert.ps1
#
# Run in elevated PowerShell (Run as Administrator) on each target machine that needs
# to install CentroidX MSIX packages signed with the sideload certificate.
#
# PURPOSE:
#   Imports the CentroidX self-signed sideload certificate to the LocalMachine\TrustedPeople
#   store. This allows MSIX packages signed with this cert to be installed without requiring
#   Developer Mode or triggering extra Windows security dialogs.
#
# WHY TrustedPeople (NOT Root):
#   Importing to LocalMachine\Root triggers an additional Windows security dialog warning
#   even from elevated processes. TrustedPeople is the correct store for sideload MSIX certs
#   and does not produce this warning.
#
# USAGE:
#   # With default path (centroidx-sideload.pfx in current directory):
#   .\install-cert.ps1
#
#   # With explicit path:
#   .\install-cert.ps1 -PfxPath "C:\path\to\centroidx-sideload.pfx"
#
#   # With password parameter (for automation):
#   .\install-cert.ps1 -PfxPath "centroidx-sideload.pfx" -Password (ConvertTo-SecureString "pwd" -AsPlainText -Force)

#Requires -RunAsAdministrator

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$PfxPath = "centroidx-sideload.pfx",

    [Parameter(Mandatory = $false)]
    [System.Security.SecureString]$Password = $null
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ExpectedCnFragment = "2F2634E3-C7B6-45A4-A112-0D039FC2ECDB"
$TrustedPeopleStore = "Cert:\LocalMachine\TrustedPeople"

Write-Host ""
Write-Host "====================================================="
Write-Host "  CentroidX Sideload Certificate Installation"
Write-Host "====================================================="
Write-Host ""

# Resolve PFX path
if (-not [IO.Path]::IsPathRooted($PfxPath)) {
    $PfxPath = Join-Path (Get-Location) $PfxPath
}

if (-not (Test-Path $PfxPath)) {
    Write-Error "PFX file not found: $PfxPath"
    Write-Host ""
    Write-Host "Provide the path to centroidx-sideload.pfx via the -PfxPath parameter."
    Write-Host "The PFX file is generated by scripts\generate-cert.ps1 and must be"
    Write-Host "distributed securely to target machines."
    exit 1
}

Write-Host "PFX file: $PfxPath"
Write-Host "Target store: $TrustedPeopleStore"
Write-Host ""

# Prompt for password if not provided
if ($null -eq $Password) {
    Write-Host "Enter the PFX password (set when generate-cert.ps1 was run)."
    $Password = Read-Host -Prompt "PFX Password" -AsSecureString
}

Write-Host ""
Write-Host "Importing certificate to $TrustedPeopleStore ..."

$imported = Import-PfxCertificate `
    -FilePath $PfxPath `
    -CertStoreLocation $TrustedPeopleStore `
    -Password $Password

Write-Host ""
Write-Host "Import completed."
Write-Host "  Thumbprint: $($imported.Thumbprint)"
Write-Host "  Subject:    $($imported.Subject)"
Write-Host "  NotAfter:   $($imported.NotAfter)"
Write-Host ""

# Verify import succeeded by querying the store
Write-Host "Verifying certificate in $TrustedPeopleStore ..."
$found = Get-ChildItem $TrustedPeopleStore | Where-Object { $_.Subject -like "*$ExpectedCnFragment*" }

if ($null -eq $found -or @($found).Count -eq 0) {
    Write-Error "Certificate NOT found in $TrustedPeopleStore after import. Something went wrong."
    exit 1
}

Write-Host ""
Write-Host "====================================================="
Write-Host "  SUCCESS"
Write-Host "====================================================="
Write-Host "  Certificate verified in $TrustedPeopleStore"
Write-Host "  Thumbprint: $($found.Thumbprint)"
Write-Host "  Subject:    $($found.Subject)"
Write-Host ""
Write-Host "  CentroidX MSIX packages signed with this certificate"
Write-Host "  can now be installed on this machine."
Write-Host "====================================================="
