# install-cert.ps1
#
# Run in elevated PowerShell (Run as Administrator) on each target machine that needs
# to install CentroidX MSIX packages signed with the sideload certificate.
#
# PURPOSE:
#   Imports the CentroidX self-signed sideload certificate to the LocalMachine\TrustedPeople
#   store. This allows MSIX packages signed with this cert to be installed without requiring
#   Developer Mode or triggering extra Windows security dialogs.
#
# TWO STORES, ONE CERTIFICATE:
#   TrustedPeople is what Add-AppxPackage checks, and it alone is enough to install.
#   Root is what makes Windows NAME the publisher -- without it, every approval prompt
#   the app or the version manager raises says "Unknown publisher", which is the moment
#   an operator most needs to recognise who is asking. Importing to Root costs one extra
#   Windows security dialog here, during setup, and removes an anonymous prompt from
#   every install and update afterwards.
#
# USAGE:
#   # With default path (centroidx-sideload.pfx in current directory):
#   .\install-cert.ps1
#
#   # With explicit path:
#   .\install-cert.ps1 -PfxPath "C:\path\to\centroidx-sideload.pfx"
#
#   # With password parameter (for automation):
#   .\install-cert.ps1 -PfxPath "centroidx-sideload.pfx" -Password (ConvertTo-SecureString "pwd" -AsPlainText -Force)

#Requires -RunAsAdministrator

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$PfxPath = "centroidx-sideload.pfx",

    [Parameter(Mandatory = $false)]
    [System.Security.SecureString]$Password = $null
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ExpectedCnFragment = "CN=Centroid"
$TrustedPeopleStore = "Cert:\LocalMachine\TrustedPeople"
$RootStore          = "Cert:\LocalMachine\Root"

Write-Host ""
Write-Host "====================================================="
Write-Host "  CentroidX Sideload Certificate Installation"
Write-Host "====================================================="
Write-Host ""

# Resolve PFX path
if (-not [IO.Path]::IsPathRooted($PfxPath)) {
    $PfxPath = Join-Path (Get-Location) $PfxPath
}

if (-not (Test-Path $PfxPath)) {
    Write-Error "PFX file not found: $PfxPath"
    Write-Host ""
    Write-Host "Provide the path to centroidx-sideload.pfx via the -PfxPath parameter."
    Write-Host "The PFX file is generated by scripts\generate-cert.ps1 and must be"
    Write-Host "distributed securely to target machines."
    exit 1
}

Write-Host "PFX file: $PfxPath"
Write-Host "Target stores: $TrustedPeopleStore and $RootStore"
Write-Host ""

# Prompt for password if not provided
if ($null -eq $Password) {
    Write-Host "Enter the PFX password (set when generate-cert.ps1 was run)."
    $Password = Read-Host -Prompt "PFX Password" -AsSecureString
}

Write-Host ""
Write-Host "Importing certificate to $TrustedPeopleStore ..."

$imported = Import-PfxCertificate `
    -FilePath $PfxPath `
    -CertStoreLocation $TrustedPeopleStore `
    -Password $Password

Write-Host ""
Write-Host "Importing certificate to $RootStore (so prompts name the publisher) ..."
Import-PfxCertificate `
    -FilePath $PfxPath `
    -CertStoreLocation $RootStore `
    -Password $Password | Out-Null

Write-Host ""
Write-Host "Import completed."
Write-Host "  Thumbprint: $($imported.Thumbprint)"
Write-Host "  Subject:    $($imported.Subject)"
Write-Host "  NotAfter:   $($imported.NotAfter)"
Write-Host ""

# Verify import succeeded by querying the store
Write-Host "Verifying certificate in $TrustedPeopleStore ..."
$found = Get-ChildItem $TrustedPeopleStore | Where-Object { $_.Subject -like "*$ExpectedCnFragment*" }

if ($null -eq $found -or @($found).Count -eq 0) {
    Write-Error "Certificate NOT found in $TrustedPeopleStore after import. Something went wrong."
    exit 1
}

Write-Host ""
Write-Host "====================================================="
Write-Host "  SUCCESS"
Write-Host "====================================================="
Write-Host "  Certificate verified in $TrustedPeopleStore"
Write-Host "  Thumbprint: $($found.Thumbprint)"
Write-Host "  Subject:    $($found.Subject)"
Write-Host ""
Write-Host "  CentroidX MSIX packages signed with this certificate"
Write-Host "  can now be installed on this machine, and approval"
Write-Host "  prompts name Centroid instead of Unknown."
Write-Host "====================================================="
