name: Build Flutter eLinux Artifacts

on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'  # Triggers the workflow when a new tag is pushed
  pull_request:

jobs:
  build-elinux:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
        repository-projects: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config libgtk-3-dev \
            liblzma-dev curl unzip xz-utils zip libglu1-mesa

      - name: Clone flutter-elinux
        run: |
          git clone https://github.com/sony/flutter-elinux.git $HOME/flutter-elinux
          echo "$HOME/flutter-elinux/bin" >> $GITHUB_PATH

      - name: Set up flutter-elinux
        run: |
          flutter-elinux --version
          flutter-elinux precache
          flutter-elinux doctor

      - name: Get Flutter Packages
        working-directory: example
        run: flutter-elinux pub get

      - name: Build for eLinux
        working-directory: example
        run: flutter-elinux build elinux --release

      - name: Package Artifacts
        working-directory: example
        run: tar -czvf example-elinux.tar.gz -C build/elinux/x64/release/bundle .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-elinux
          path: example/example-elinux.tar.gz

    # TODO remove

      - name: Get release
        if: startsWith(github.ref, 'refs/tags/v')
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Release tar file
        if: startsWith(github.ref, 'refs/tags/v')
        id: upload-release-asset-tar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: example/example-elinux.tar.gz
          asset_name: example-elinux.tar.gz
          asset_content_type: application/x-tar
